// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public partial class Breed
    {
        public string PetBreed { get; set; }
        public int IdPetType { get; set; }

        public virtual Pettype IdPetTypeNavigation { get; set; }
    }
}