// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public class Domain
    {
     
        public string Description { get; set; }
        public bool IsDisabled { get; set; }
        public int IdDescriptable { get; set; }
        public bool IsReported { get; set; }
        public string UserName { get; set; }


    


    }
}