// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public  class Location
    {

        public int IdLocation { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int Level { get; set; }
        public bool IsHouse { get; set; }


    }
}