// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public  class Messages
    {
        public int Idmessages { get; set; }
        public string Body { get; set; }
        public DateTime Timestamp { get; set; }
        public int IdPersonFrom { get; set; }
        public int IdPersonTo { get; set; }
        public string UserName { get; set; }

    }
}