// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public partial class Period
    {
       
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int IdPeriod { get; set; }

       
    }
}