// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public  class Pettype
    {
    

        public int IdPetType { get; set; }
        public string TypePetName { get; set; }

    }
}