// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public partial class Review
    {
      
        public int Grade { get; set; }
        public int IdDescriptable { get; set; }
        public string UserName { get; set; }

        
    }
}