// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Adlisting
    {
        public string Description { get; set; }
        public double Price { get; set; }
        public int IdAdListing { get; set; }
        public int IdDescriptable { get; set; }
        public string UserName { get; set; }
        public int? IdLocation { get; set; }
        public int? IdPeriod { get; set; }

        public virtual Descriptable IdDescriptableNavigation { get; set; }
        public virtual Location IdLocationNavigation { get; set; }
        public virtual Period IdPeriodNavigation { get; set; }
        public virtual Appuser UserNameNavigation { get; set; }
    }
}