// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Admin
    {
        public Admin()
        {
            Descriptable = new HashSet<Descriptable>();
        }

        public string UserName { get; set; }

        public virtual Person UserNameNavigation { get; set; }
        public virtual ICollection<Descriptable> Descriptable { get; set; }
    }
}