// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Appuser
    {
        public Appuser()
        {
            Adlisting = new HashSet<Adlisting>();
            Pet = new HashSet<Pet>();
            Review = new HashSet<Review>();
            IdDescriptable = new HashSet<Review>();
            IdDescriptableNavigation = new HashSet<Descriptable>();
        }

        public string Oib { get; set; }
        public bool Smoker { get; set; }
        public string Birthday { get; set; }
        public string Gender { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public bool IsDisable { get; set; }
        public string UserName { get; set; }

        public virtual Person UserNameNavigation { get; set; }
        public virtual Card Card { get; set; }
        public virtual ICollection<Adlisting> Adlisting { get; set; }
        public virtual ICollection<Pet> Pet { get; set; }
        public virtual ICollection<Review> Review { get; set; }

        public virtual ICollection<Review> IdDescriptable { get; set; }
        public virtual ICollection<Descriptable> IdDescriptableNavigation { get; set; }
    }
}