// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Card
    {
        public string CardNumber { get; set; }
        public string ValidUntil { get; set; }
        public string Cvv { get; set; }
        public string Address { get; set; }
        public string CardType { get; set; }
        public string UserName { get; set; }

        public virtual Appuser UserNameNavigation { get; set; }
    }
}