// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Descriptable
    {
        public Descriptable()
        {
            Adlisting = new HashSet<Adlisting>();
            Pet = new HashSet<Pet>();
            UserName1 = new HashSet<Appuser>();
        }

        public string Description { get; set; }
        public bool IsDisabled { get; set; }
        public int IdDescriptable { get; set; }
        public bool IsReported { get; set; }
        public string UserName { get; set; }

        public virtual Admin UserNameNavigation { get; set; }
        public virtual Review Review { get; set; }
        public virtual ICollection<Adlisting> Adlisting { get; set; }
        public virtual ICollection<Pet> Pet { get; set; }

        public virtual ICollection<Appuser> UserName1 { get; set; }
    }
}