// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Messages
    {
        public Messages()
        {
            UserName1 = new HashSet<Person>();
        }

        public int Idmessages { get; set; }
        public string Body { get; set; }
        public DateTime Timestamp { get; set; }
        public int IdPersonFrom { get; set; }
        public int IdPersonTo { get; set; }
        public string UserName { get; set; }

        public virtual Person UserNameNavigation { get; set; }

        public virtual ICollection<Person> UserName1 { get; set; }
    }
}