// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Period
    {
        public Period()
        {
            Adlisting = new HashSet<Adlisting>();
        }

        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int IdPeriod { get; set; }

        public virtual ICollection<Adlisting> Adlisting { get; set; }
    }
}