// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Person
    {
        public Person()
        {
            Messages = new HashSet<Messages>();
            Idmessages = new HashSet<Messages>();
        }

        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string MobileNumber { get; set; }
        public int IdPerson { get; set; }

        public virtual Admin Admin { get; set; }
        public virtual Appuser Appuser { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }

        public virtual ICollection<Messages> Idmessages { get; set; }
    }
}