// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Pettype
    {
        public Pettype()
        {
            Pet = new HashSet<Pet>();
        }

        public int IdPetType { get; set; }
        public string TypePetName { get; set; }

        public virtual Breed Breed { get; set; }
        public virtual ICollection<Pet> Pet { get; set; }
    }
}