// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.EFModel
{
    public partial class Review
    {
        public Review()
        {
            UserNameNavigation = new HashSet<Appuser>();
        }

        public int Grade { get; set; }
        public int IdDescriptable { get; set; }
        public string UserName { get; set; }

        public virtual Descriptable IdDescriptableNavigation { get; set; }
        public virtual Appuser UserName1 { get; set; }

        public virtual ICollection<Appuser> UserNameNavigation { get; set; }
    }
}