// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure5.EFModel
{
    public partial class AdListing
    {
        public AdListing()
        {
            PersonRole = new HashSet<PersonRole>();
        }

        public int AdlistingId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? IdAdress { get; set; }
        public string AdlistingDescription { get; set; }
        public bool? IsActive { get; set; }
        public double? Price { get; set; }
        public string Title { get; set; }
        public int PetId { get; set; }

        public virtual Adress IdAdressNavigation { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual ICollection<PersonRole> PersonRole { get; set; }
    }
}