// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure5.EFModel
{
    public partial class Adress
    {
        public Adress()
        {
            AdListing = new HashSet<AdListing>();
        }

        public int AdressId { get; set; }
        public string Adress1 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public bool? IsHouse { get; set; }
        public int? Floor { get; set; }

        public virtual ICollection<AdListing> AdListing { get; set; }
    }
}