// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure5.EFModel
{
    public partial class HasPet
    {
        public int PersonId { get; set; }
        public int? PetId { get; set; }
    }
}