// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure5.EFModel
{
    public partial class PersonRole
    {
        public int PersonId { get; set; }
        public int AdlistingId { get; set; }
        public DateTime AssigmentDate { get; set; }
        public int RoleId { get; set; }

        public virtual AdListing Adlisting { get; set; }
        public virtual Person Person { get; set; }
        public virtual Role Role { get; set; }
    }
}