// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure5.EFModel
{
    public partial class Person
    {
        public int PersonId { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonLastName { get; set; }
        public string Oib { get; set; }
        public string PersonEmail { get; set; }
        public string PersonMobile { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SessionId { get; set; }

        public virtual PersonRole PersonRole { get; set; }
    }
}