// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure5.EFModel
{
    public partial class Pet
    {
        public Pet()
        {
            AdListing = new HashSet<AdListing>();
        }

        public int PetId { get; set; }
        public string PetName { get; set; }
        public bool? Sex { get; set; }
        public string Size { get; set; }
        public string PetType { get; set; }
        public string Breed { get; set; }

        public virtual ICollection<AdListing> AdListing { get; set; }
    }
}